version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
            - "4431:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs:/var/log/nginx
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
